
["Keyword config"]
	#This config allows for faster implementation of new thirst quenching items. It works by defining
	#lists of regular expressions to select items by their id name. It divides the items into categories
	#that have preset values for hydration and quenching
	#If the keyword config should be taken into consideration
	enableKeywordConfig = true

	["Keyword config"."Default Hydration values"]
		#Default hydration for drinks selected with keywords [0-20]
		defaultDrinkHydration = 8
		#Default quenchness for drinks selected with keywords [0-20]
		defaultDrinkQuenchness = 10
		#Default hydration for soups selected with keywords [0-20]
		defaultSoupHydration = 2
		#Default quenchness for soups selected with keywords [0-20]
		defaultSoupQuenchness = 2
		#Default hydration for fruits selected with keywords [0-20]
		defaultFruitHydration = 2
		#Default quenchness for fruits selected with keywords [0-20]
		defaultFruitQuenchness = 2

		["Keyword config"."Default Hydration values"."Blacklisted Keywords"]
			#The list of items to be ignored if they get selected by mistake by other keywords
			#Format: [(keyword1|keyword2|keyword3)]
			keyword_blacklist = "(?:\\b|[^a-zA-Z])(pepper|salt|empty|nut|baked|meat|grilled|barbeque|chilli|spicy|spiced|hot|sandwhich|tart|bread|dried|candied|leaf|leaves|gummy|crate|jam|sauce|bucket|seed|cookie|pie|bush|sapling|bean|curry|cake|candy|seed|rice|sapling|shell|husk)(?:\\b|[^a-zA-Z])"

		["Keyword config"."Default Hydration values"."Drink Keywords"]
			#List of keywords for drinks
			#Format: [(keyword1|keyword2|keyword3)]
			keyword_drink = "(?:\\b|[^a-zA-Z])(drink|juice|tea|soda|coffee|wine|beer|cider|yogurt|milkshake|smoothie|milk|mate|lemonade|terer|latte)(?:\\b|[^a-zA-Z])"

		["Keyword config"."Default Hydration values"."Soup Keywords"]
			#List of keywords for soups
			#Format: [(keyword1|keyword2|keyword3)]
			keyword_soup = "(?:\\b|[^a-zA-Z])(soup|stew|porridge|custard)(?:\\b|[^a-zA-Z])"

		["Keyword config"."Default Hydration values"."Fruit Keywords"]
			#List of keywords for fruits
			#Format: [(keyword1|keyword2|keyword3)]
			keyword_fruit = "(?:\\b|[^a-zA-Z])(fruit|berry|berries|grape|orange|peach|pear|coconut|lemon|melon|cherry|cherries|apple|pulp|pomelo|citron)(?:\\b|[^a-zA-Z])"

