
[Settings]
	#Determines whether a weight will be applied to mobs.
	isMobsAffected = false
	#Determines whether weight will depend on the protection value.
	isDependsOnProtection = true

[Thresholds]
	#Determines from which weight level the corresponding effect will be applied.
	#The values must be in the range [0, 19] and be greater than the previous threshold value.
	#Encumbrance I threshold.
	Level1EffectThreshold = 6
	#Encumbrance II threshold.
	Level2EffectThreshold = 10
	#Encumbrance III threshold.
	Level3EffectThreshold = 15

[Weight]
	#Determines the weight of armor elements. Values must be in the range [0, 20].
	#Example:"[mod_id]:[item_id]" = [value].
	"minecraft:leather_helmet" = 0.5
	"minecraft:leather_chestplate" = 1.0
	"minecraft:leather_leggings" = 1.0
	"minecraft:leather_boots" = 0.5
	"minecraft:chainmail_helmet" = 1.5
	"minecraft:chainmail_chestplate" = 2.0
	"minecraft:chainmail_leggings" = 2.0
	"minecraft:chainmail_boots" = 1.5
	"minecraft:iron_helmet" = 2.0
	"minecraft:iron_chestplate" = 3.0
	"minecraft:iron_leggings" = 3.0
	"minecraft:iron_boots" = 2.0
	"minecraft:golden_helmet" = 2.0
	"minecraft:golden_chestplate" = 3.0
	"minecraft:golden_leggings" = 3.0
	"minecraft:golden_boots" = 2.0
	"minecraft:diamond_helmet" = 3.0
	"minecraft:diamond_chestplate" = 5.0
	"minecraft:diamond_leggings" = 5.0
	"minecraft:diamond_boots" = 3.0
	"minecraft:netherite_helmet" = 3.5
	"minecraft:netherite_chestplate" = 6
	"minecraft:netherite_leggings" = 6
	"minecraft:netherite_boots" = 3.5
	"minecraft:turtle_helmet" = 3.0
	"easy_emerald:copper_head" = 1.0
	"easy_emerald:copper_leggings" = 1.8

